prime1-prime-generator: prime1-prime-generator.c
	gcc -Wall -g -DDEBUG prime1-prime-generator.c -o prime1-prime-generator
prime1-prime-generator-cpp: prime1-prime-generator.cpp
	g++ -Wall -DDEBUG prime1-prime-generator.cpp -o prime1-prime-generator-cpp
prime-simple-sieve: prime-simple-sieve.c
	gcc -Wall -DDEBUG prime-simple-sieve.c -o prime-simple-sieve
prime-test: prime-test.c
	gcc -Wall -DDEBUG prime-test.c -o prime-test
