#!/bin/bash - 
#===============================================================================
#
#          FILE: mp32ogg.sh
# 
#         USAGE: ./mp32ogg.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: liuxueyang (lxy), liuxueyang457@163.com
#  ORGANIZATION: Hunan University
#       CREATED: 2016年04月11日 16:19
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

mpg321 "$1.mp3" -w - | oggenc -o "$1.ogg" -

echo "Success:-) by Lpaste"

