3-1: 3-1.c
	gcc -Wall -DDEBUG 3-1.c -o 3-1
3-2: 3-2.c
	gcc -Wall -DDEBUG 3-2.c -o 3-2
3-3: 3-3.c
	gcc -Wall -DDEBUG 3-3.c -o 3-3
3-4: 3-4.c
	gcc -Wall -DDEBUG 3-4.c -o 3-4
3-5: 3-5.c
	gcc -Wall -DDEBUG 3-5.c -o 3-5
3-6: 3-6.c
	gcc -Wall -DDEBUG 3-6.c -o 3-6
3-7: 3-7.c
	gcc -Wall -DDEBUG 3-7.c -o 3-7
uva-340: uva-340.c
	gcc -Wall -DDEBUG uva-340.c -o uva-340
uva-1583: uva-1583.c
	gcc -Wall -DDEBUG uva-1583.c -o uva-1583
