3-1: 3-1.c
	gcc -Wall -DDEBUG 3-1.c -o 3-1
3-2: 3-2.c
	gcc -Wall -DDEBUG 3-2.c -o 3-2
3-3: 3-3.c
	gcc -Wall -DDEBUG 3-3.c -o 3-3
3-4: 3-4.c
	gcc -Wall -DDEBUG 3-4.c -o 3-4
3-5: 3-5.c
	gcc -Wall -DDEBUG 3-5.c -o 3-5
3-6: 3-6.c
	gcc -Wall -DDEBUG 3-6.c -o 3-6
3-7: 3-7.c
	gcc -Wall -DDEBUG 3-7.c -o 3-7
3-8: 3-8.c
	gcc -Wall -DDEBUG 3-8.c -o 3-8
3-9: 3-9.c
	gcc -Wall -DDEBUG 3-9.c -o 3-9
3-10: 3-10.c
	gcc -Wall -DDEBUG 3-10.c -o 3-10
3-11: 3-11.c
	gcc -Wall -DDEBUG 3-11.c -o 3-11
3-12: 3-12.c
	gcc -Wall -DDEBUG 3-12.c -o 3-12
3-13: 3-13.c
	gcc -Wall -DDEBUG 3-13.c -o 3-13
