3-1: 3-1.c
	gcc -Wall -DDEBUG 3-1.c -o 3-1
3-2: 3-2.c
	gcc -Wall -DDEBUG 3-2.c -o 3-2
3-3: 3-3.c
	gcc -Wall -DDEBUG 3-3.c -o 3-3
3-4: 3-4.c
	gcc -Wall -DDEBUG 3-4.c -o 3-4
3-5: 3-5.c
	gcc -Wall -DDEBUG 3-5.c -o 3-5
3-6: 3-6.c
	gcc -Wall -DDEBUG 3-6.c -o 3-6
3-7: 3-7.c
	gcc -Wall -DDEBUG 3-7.c -o 3-7
uva-340: uva-340.c
	gcc -Wall -DDEBUG uva-340.c -o uva-340
uva-1583: uva-1583.c
	gcc -Wall -DDEBUG uva-1583.c -o uva-1583
uva-1584: uva-1584.c
	gcc -Wall -DDEBUG uva-1584.c -o uva-1584
uva-1585: uva-1585.c
	gcc -Wall -DDEBUG uva-1585.c -o uva-1585
uva-1586: uva-1586.c
	gcc -Wall -DDEBUG uva-1586.c -o uva-1586
uva-1225: uva-1225.c
	gcc -Wall -DDEBUG uva-1225.c -o uva-1225
uva-455: uva-455.c
	gcc -Wall -DDEBUG uva-455.c -o uva-455
uva-227: uva-227.c
	gcc -Wall -DDEBUG uva-227.c -o uva-227
uva-227-test: uva-227-test.c
	gcc -Wall -DDEBUG uva-227-test.c -o uva-227-test
uva-232: uva-232.c
	gcc -Wall -DDEBUG uva-232.c -o uva-232
uva-1368: uva-1368.c
	gcc -Wall -DDEBUG uva-1368.c -o uva-1368
uva-202: uva-202.c
	gcc -Wall -DDEBUG uva-202.c -o uva-202
uva-10340: uva-10340.c
	gcc -Wall -DDEBUG uva-10340.c -o uva-10340
uva-1587: uva-1587.c
	gcc -Wall -DDEBUG uva-1587.c -o uva-1587
uva-1588: uva-1588.c
	gcc -Wall -DDEBUG uva-1588.c -o uva-1588
uva-11809: uva-11809.c
	gcc -Wall -DDEBUG uva-11809.c -o uva-11809
uva-10340++: uva-10340.cpp
	g++ -Wall -DDEBUG uva-10340.cpp -o uva-10340++
