compress: compress.cpp
	g++ -Wall -o compress compress.cpp
sizeof: sizeof.cpp
	g++ -Wall -o sizeof sizeof.cpp
cpp11: cpp11.cpp
	g++-5 -Wall -o cpp11 cpp11.cpp
bounds1: bounds1.cpp algostuff.hpp
	g++-5 --std=c++1y -Wall -o bounds1 bounds1.cpp
vector: vector.cpp algostuff.hpp
	g++-5 --std=c++1y -Wall -o vector vector.cpp
map: map.cpp algostuff.hpp
	g++-5 --std=c++1y -Wall -o map map.cpp
